name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: adrienbrignon/epitech-c
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: make test
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          directory: .
          fail_ci_if_error: false
